import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/library/providers/themeprovider";
import { ReactQueryProvider } from "@/library/providers/reactqueryprovider";
// import { QueryClientProvider } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trykey",
  description:
    "Trykey is making use of robotics, artificial intelligence and blockchain to help investors track the income generated by their physical assets in any location world wide",
  openGraph: {
    images: [
      {
        url: "opengraph-image.png",
        alt: "trykey landing page",
      },
    ],
    type: "website",
    url: "https://www.trykeyprotocol.com/",
    title: "Trykey",
    description:
      "Trykey is making use of robotics, artificial intelligence and blockchain to help investors track the income generated by their physical assets in any location world wide",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
